[package]
name = "search_api"
version = "0.1.1"
authors = ["WincerChan <WincerChan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tantivy = "0.14.0"
cang-jie = "0.11.1"
jieba-rs = "0.6.2"
toml = "0.5"

[patch.crates-io]
cang-jie = { path = "/Users/loerfy/Terms/cang-jie/" }